button_actions:
  "0":
    file: tasks/time.py
    func: fetch_time
  "1":
    file: tasks/weather.py
    func: fetch_weather_today
    kwargs:
      area_code: "270000"
      area_name: "大阪"
  # private examples
  # "2":
  #   file: tasks/private/custom.py
  #   func: secret_action

